#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo "=== Generating version info ==="
VERSION=$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" Info.plist)
COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
mkdir -p Sources/UVieMac/Generated
cat > Sources/UVieMac/Generated/Version.swift <<EOF
// Auto-generated by build.sh. Do not edit manually.
enum AppVersion {
    static let version = "$VERSION"
    static let commitHash = "$COMMIT"
    static let fullVersion = "v\(version)-\(commitHash)"
}
EOF

# Ensure the Rust engine library is available for linking.
# Priority: UVIE_RS_DIR (local development) > prebuilt Frameworks > fetch from GitHub release.
if [ -n "$UVIE_RS_DIR" ]; then
    echo "=== Building uvie-rs from local source ($UVIE_RS_DIR) ==="
    (
        cd "$UVIE_RS_DIR"
        cargo build --release --target aarch64-apple-darwin
        cargo build --release --target x86_64-apple-darwin
    )
    mkdir -p Frameworks
    lipo -create \
        "$UVIE_RS_DIR/target/aarch64-apple-darwin/release/libuvie.a" \
        "$UVIE_RS_DIR/target/x86_64-apple-darwin/release/libuvie.a" \
        -output Frameworks/libuvie.a
    cp "$UVIE_RS_DIR/include/uvie.h" Frameworks/uvie.h
elif [ ! -f "Frameworks/libuvie.a" ]; then
    echo "=== uvie library not found in Frameworks/, fetching prebuilt release ==="
    ./scripts/fetch-uvie.sh
fi

echo "=== Building UVieMac ==="
swift build "$@"

echo "Build complete! (${SECONDS}s)"
echo "=== Build complete ==="
